#!/usr/bin/env bash
# installs ngix to server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo service nginx start
string="server_name selidex.tech;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}"
e404="\terror_page 404 \/error404.html;\n\tlocation = \/error404.html {\n\t\tinternal;\n\t}"
comb="${string}\n${e404}"
sudo sed -i "s/server_name _;/$comb/" /etc/nginx/sites-available/default
sudo service nginx restart
