#!/usr/bin/env bash
# sets up a server so that it runs nginx as not root
sudo pkill -f apache
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
