#!/usr/bin/env bash
# sets up a server so that it runs nginx as not root
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sed -i "server {listen 8080;}" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
